server:
  port: 9000
  servlet-path: /

spring:
  application:
    name: ONS cfDatabaseTool
  datasource:
    username: ${cloud.services.postgresql.connection.username}
    password: ${cloud.services.postgresql.connection.password}
    url: ${cloud.services.postgresql.connection.jdbcurl}
    driverClassName: org.postgresql.Driver
    tomcat:
      initial-size: 5
      max-active: 10
      max-idle: 5
      min-idle: 3
